export const GET_MEMBERS_START = 'GITHUB/GET_MEMBERS_START';
export const GET_MEMBERS_SUCCEED = 'GITHUB/GET_MEMBERS_SUCCEED';
export const GET_MEMBERS_FAIL = 'GITHUB/GET_MEMBERS_FAIL';
export const SEARCH_REPOSITORIES_START = 'GITHUB/SEARCH_REPOSITORIES_START';
export const SEARCH_REPOSITORIES_SUCCEED = 'GITHUB/SEARCH_REPOSITORIES_SUCCEED';
export const SEARCH_REPOSITORIES_FAIL = 'GITHUB/SEARCH_REPOSITORIES_FAIL';
