import { User } from '../models';

const users: User[] = [
  {
    login: 'gaearon',
    id: 810438,
    nodeId: 'MDQ6VXNlcjgxMDQzOA=="',
    avatarUrl: 'https://avatars0.githubusercontent.com/u/810438?v=4',
    gravatarId: '',
    url: 'https://api.github.com/users/gaearon',
    htmlUrl: 'https://github.com/',
    followersUrl: 'https://api.github.com/users/gaearon/followers',
    followingUrl: 'https://api.github.com/users/gaearon/following{/other_user}',
    gistsUrl: 'https://api.github.com/users/gaearon/gists{/gist_id}',
    starredUrl: 'https://api.github.com/users/gaearon/starred{/owner}{/repo}',
    subscriptionsUrl: 'https://api.github.com/users/gaearon/subscriptions',
    organizationsUrl: 'https://api.github.com/users/gaearon/orgs',
    reposUrl: 'https://api.github.com/users/gaearon/repos',
    eventsUrl: 'https://api.github.com/users/gaearon/events{/privacy}',
    receivedEventsUrl: 'https://api.github.com/users/gaearon/received_events',
    type: 'User',
    siteAdmin: false,
  },
  {
    login: 'sophiebits',
    id: 6829,
    nodeId: 'MDQ6VXNlcjY4MjA=',
    avatarUrl: 'https://avatars2.githubusercontent.com/u/6820?v=4',
    gravatarId: '',
    url: 'https://api.github.com/users/sophiebits',
    htmlUrl: 'https://github.com/sophiebits',
    followersUrl: 'https://api.github.com/users/sophiebits/followers',
    followingUrl:
      'https://api.github.com/users/sophiebits/following{/other_user}',
    gistsUrl: 'https://api.github.com/users/sophiebits/gists{/gist_id}',
    starredUrl:
      'https://api.github.com/users/sophiebits/starred{/owner}{/repo}',
    subscriptionsUrl: 'https://api.github.com/users/sophiebits/subscriptions',
    organizationsUrl: 'https://api.github.com/users/sophiebits/orgs',
    reposUrl: 'https://api.github.com/users/sophiebits/repos',
    eventsUrl: 'https://api.github.com/users/sophiebits/events{/privacy}',
    receivedEventsUrl:
      'https://api.github.com/users/sophiebits/received_events',
    type: 'User',
    siteAdmin: false,
  },
  {
    login: 'sebmarkbage',
    id: 63648,
    nodeId: 'MDQ6VXNlcjYzNjQ4',
    avatarUrl: 'https://avatars2.githubusercontent.com/u/63648?v=4',
    gravatarId: '',
    url: 'https://api.github.com/users/sebmarkbage',
    htmlUrl: 'httpGs://github.com/sebmarkbage',
    followersUrl: 'https://api.github.com/users/sebmarkbage/followers',
    followingUrl:
      'https://api.github.com/users/sebmarkbage/following{/other_user}',
    gistsUrl: 'https://api.github.com/users/sebmarkbage/gists{/gist_id}',
    starredUrl:
      'https://api.github.com/users/sebmarkbage/starred{/owner}{/repo}',
    subscriptionsUrl: 'https://api.github.com/users/sebmarkbage/subscriptions',
    organizationsUrl: 'https://api.github.com/users/sebmarkbage/orgs',
    reposUrl: 'https://api.github.com/users/sebmarkbage/repos',
    eventsUrl: 'https://api.github.com/users/sebmarkbage/events{/privacy}',
    receivedEventsUrl:
      'https://api.github.com/users/sebmarkbage/received_events',
    type: 'User',
    siteAdmin: false,
  },
  {
    login: 'acdlite',
    id: 3624098,
    nodeId: 'MDQ6VXNlcjM2MjQwOTg=',
    avatarUrl: 'https://avatars0.githubusercontent.com/u/3624098?v=4',
    gravatarId: '',
    url: 'https://api.github.com/users/acdlite',
    htmlUrl: 'https://github.com/acdlite',
    followersUrl: 'https://api.github.com/users/acdlite/followers',
    followingUrl: 'https://api.github.com/users/acdlite/following{/other_user}',
    gistsUrl: 'https://api.github.com/users/acdlite/gists{/gist_id}',
    starredUrl: 'https://api.github.com/users/acdlite/starred{/owner}{/repo}',
    subscriptionsUrl: 'https://api.github.com/users/acdlite/subscriptions',
    organizationsUrl: 'https://api.github.com/users/acdlite/orgs',
    reposUrl: 'https://api.github.com/users/acdlite/repos',
    eventsUrl: 'https://api.github.com/users/acdlite/events{/privacy}',
    receivedEventsUrl: 'https://api.github.com/users/acdlite/received_events',
    type: 'User',
    siteAdmin: false,
  },
  {
    login: 'vjeux',
    id: 197597,
    nodeId: 'MDQ6VXNlcjE5NzU5Nw==',
    avatarUrl: 'https://avatars0.githubusercontent.com/u/197597?v=4',
    gravatarId: '',
    url: 'https://api.github.com/users/vjeux',
    htmlUrl: 'https://github.com/vjeux',
    followersUrl: 'https://api.github.com/users/vjeux/followers',
    followingUrl: 'https://api.github.com/users/vjeux/following{/other_user}',
    gistsUrl: 'https://api.github.com/users/vjeux/gists{/gist_id}',
    starredUrl: 'https://api.github.com/users/vjeux/starred{/owner}{/repo}',
    subscriptionsUrl: 'https://api.github.com/users/vjeux/subscriptions',
    organizationsUrl: 'https://api.github.com/users/vjeux/orgs',
    reposUrl: 'https://api.github.com/users/vjeux/repos',
    eventsUrl: 'https://api.github.com/users/vjeux/events{/privacy}',
    receivedEventsUrl: 'https://api.github.com/users/vjeux/received_events',
    type: 'User',
    siteAdmin: false,
  },
  {
    login: 'AGS-',
    id: 7844509,
    nodeId: 'MDQ6VXNlcjc4NDQ1MDk=',
    avatarUrl: 'https://avatars0.githubusercontent.com/u/7844509?v=4',
    gravatarId: '',
    url: 'https://api.github.com/users/AGS-',
    htmlUrl: 'https://github.com/AGS-',
    followersUrl: 'https://api.github.com/users/AGS-/followers',
    followingUrl: 'https://api.github.com/users/AGS-/following{/other_user}',
    gistsUrl: 'https://api.github.com/users/AGS-/gists{/gist_id}',
    starredUrl: 'https://api.github.com/users/AGS-/starred{/owner}{/repo}',
    subscriptionsUrl: 'https://api.github.com/users/AGS-/subscriptions',
    organizationsUrl: 'https://api.github.com/users/AGS-/orgs',
    reposUrl: 'https://api.github.com/users/AGS-/repos',
    eventsUrl: 'https://api.github.com/users/AGS-/events{/privacy}',
    receivedEventsUrl: 'https://api.github.com/users/AGS-/received_events',
    type: 'User',
    siteAdmin: false,
  },
  {
    login: 'ahmed-shehata',
    id: 4982099,
    nodeId: 'MDQ6VXNlcjQ5ODIwOTk=',
    avatarUrl: 'https://avatars3.githubusercontent.com/u/4982099?v=4',
    gravatarId: '',
    url: 'https://api.github.com/users/ahmed-shehata',
    htmlUrl: 'https://github.com/ahmed-shehata',
    followersUrl: 'https://api.github.com/users/ahmed-shehata/followers',
    followingUrl:
      'https://api.github.com/users/ahmed-shehata/following{/other_user}',
    gistsUrl: 'https://api.github.com/users/ahmed-shehata/gists{/gist_id}',
    starredUrl:
      'https://api.github.com/users/ahmed-shehata/starred{/owner}{/repo}',
    subscriptionsUrl:
      'https://api.github.com/users/ahmed-shehata/subscriptions',
    organizationsUrl: 'https://api.github.com/users/ahmed-shehata/orgs',
    reposUrl: 'https://api.github.com/users/ahmed-shehata/repos',
    eventsUrl: 'https://api.github.com/users/ahmed-shehata/events{/privacy}',
    receivedEventsUrl:
      'https://api.github.com/users/ahmed-shehata/received_events',
    type: 'User',
    siteAdmin: false,
  },
  {
    login: 'AhmedSoliman',
    id: 59670,
    nodeId: 'MDQ6VXNlcjU5Njcw',
    avatarUrl: 'https://avatars0.githubusercontent.com/u/59670?v=4',
    gravatarId: '',
    url: 'https://api.github.com/users/AhmedSoliman',
    htmlUrl: 'https://github.com/AhmedSoliman',
    followersUrl: 'https://api.github.com/users/AhmedSoliman/followers',
    followingUrl:
      'https://api.github.com/users/AhmedSoliman/following{/other_user}',
    gistsUrl: 'https://api.github.com/users/AhmedSoliman/gists{/gist_id}',
    starredUrl:
      'https://api.github.com/users/AhmedSoliman/starred{/owner}{/repo}',
    subscriptionsUrl: 'https://api.github.com/users/AhmedSoliman/subscriptions',
    organizationsUrl: 'https://api.github.com/users/AhmedSoliman/orgs',
    reposUrl: 'https://api.github.com/users/AhmedSoliman/repos',
    eventsUrl: 'https://api.github.com/users/AhmedSoliman/events{/privacy}',
    receivedEventsUrl:
      'https://api.github.com/users/AhmedSoliman/received_events',
    type: 'User',
    siteAdmin: false,
  },
  {
    login: 'ajma',
    id: 136692,
    nodeId: 'MDQ6VXNlcjEzNjY5Mg==',
    avatarUrl: 'https://avatars1.githubusercontent.com/u/136692?v=4',
    gravatarId: '',
    url: 'https://api.github.com/users/ajma',
    htmlUrl: 'https://github.com/ajma',
    followersUrl: 'https://api.github.com/users/ajma/followers',
    followingUrl: 'https://api.github.com/users/ajma/following{/other_user}',
    gistsUrl: 'https://api.github.com/users/ajma/gists{/gist_id}',
    starredUrl: 'https://api.github.com/users/ajma/starred{/owner}{/repo}',
    subscriptionsUrl: 'https://api.github.com/users/ajma/subscriptions',
    organizationsUrl: 'https://api.github.com/users/ajma/orgs',
    reposUrl: 'https://api.github.com/users/ajma/repos',
    eventsUrl: 'https://api.github.com/users/ajma/events{/privacy}',
    receivedEventsUrl: 'https://api.github.com/users/ajma/received_events',
    type: 'User',
    siteAdmin: false,
  },
];

export default users;
